version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/medical-clinic
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=123
  db:
    image: med-test1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=medical-clinic
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=123